### ISSUE TITLE
Unable to connect when using SSL/TLS ( wss ) on iOS Safari and self signed cert (dev)  

### ISSUE THREAD

**Issue by MagnusThor** [MagnusThor/xsocketsAngularJS#1]
When using a self signed certificate the "provider" cannot connect.

**Comment by arins** [comment]
If you are running IIS localy
1. install openssl and add your openssl bin folder to path environment variable
   https://slproweb.com/products/Win32OpenSSL.html (light is enough)
2. run commands in cmd from a empty folder (use appropriate name for your files and use your domain that your iis uses)

openssl genrsa -out yourdomain.key 2048
openssl req -new -x509 -sha256 -key yourdomain.key -out yourdomain.cer -days 365 -subj /CN=yourdomain.com
openssl pkcs12 -export -out yourdomain.pfx -inkey yourdomain.key -in yourdomain.cer

SET A PASSWORD which will be used in IIS later
1. add your certificate (.cer file) as trusted root certificate authorities via mmc certificate snapin
2. add your pfx certificate to iis via server certificates in iis settings and type in the password from step 2
3. set your site to use the certificate
4. make sure your site works by requesing a page
5. add cert to ios by downloading the cer file and ios will ask you to install it when downloading. (by email, google drive )
